const users = [
  {
    id: 1,
    firstname: 'Obinna',
    lastname: 'Chimezie',
    othernames: 'Neville',
    email: 'Obinna932@gmail.com',
    phoneNumber: '080288209',
    username: 'thesnitch',
    registered: '3 / 25 / 2015',
    password: 'admin',
    isAdmin: false,
  },
  {
    id: 2,
    firstname: 'David',
    lastname: 'Nnamdi',
    othernames: 'Neville',
    email: 'Obinna932@gmail.com',
    phoneNumber: '080288209',
    username: 'Thecoolguy',
    registered: '3 / 25 / 2015',
    password: 'password',
    isAdmin: false,
  },
  {
    id: 3,
    firstname: 'James',
    lastname: 'Chidi',
    othernames: 'Neville',
    email: 'Obinna932@gmail.com',
    phoneNumber: '080288209',
    username: 'Thereporter',
    password: 'password',
    registered: '3 / 25 / 2015',
    isAdmin: true,
  },
];
module.exports = users;
